### ISSUE TITLE
User wants to manage information about himself in order to keep his profile up-to-date

### ISSUE THREAD

**Issue by worm2fed** [union-platform/union-app#16]
**Scope of action:**  Profile Settings Screen
**Precondition:** The user selected the "profile settings" item in the context menu on the profile screen
**Design:** https://www.figma.com/file/2St3zSul4fHnLffqy3WK7P/union-mobile?node-id=1478%3A26304

## Use cases:

1. The system displays a list of profile settings
2. The user selects the field
3. The user changes the content of the desired field
4. The system checks the correctness of the changes made and saves the changes
    (a):
        1. The system informs about incorrect input, then the script occurs from step 3

### Fields in the user profile

**Basic information**

- Name - only letters and spaces, from 4 to 32 symbols
- Mission – maximum length 500

**Contacts**

- Phone - phone validator
- Telegram - link
- Instagram - link
- LinkedIn - link
- Facebook - link

**About yourself**

- Date of birth - date
- Current city - list of cities
- Child's dream - text
- Main motivation – text

**Additional information**

- Belief in a higher power - text
- Hobby - text
- The meaning of life - text

-----
**Область действия:**  Экран настроек профиля
**Предусловие:** Пользователя выбрал пункт “настройки профиля” в контекстном меню на экране своего профиля
**Дизайн:** https://www.figma.com/file/2St3zSul4fHnLffqy3WK7P/union-mobile?node-id=1478%3A26304

## Сценарий:

1. Система отображает список настроек профиля
2. Пользователь выбирает поле
3. Пользователь изменяет содержимое интересующего поля
4. Система проверяет корректность внесённых изменений и сохраняет изменения
    (а):
        1. Система информирует о некорректном вводе, далее сценарий происходит с шага 3

### Поля в профиле пользователя

**Основная информация**

- Имя - только буквы и пробельный символ, от 4 до 32 символов
- Миссия – максимальная длина 500

**Контакты**

- Телефон - валидатор телефона
- Telegram - ссылка
- Instagram - ссылка
- LinkedIn - ссылка
- Facebook - ссылка

**О себе**

- Дата рождения - дата
- Текущий город - список городов
- Детская мечта – текст
- Основная мотивация – текст

**Дополнительная информация**

- Вера в высшую силу – текст
- Хобби – текст
- Смысл жизни - текст

**Comment by worm2fed** [comment]
@rexolion I would like to change phone number in another flow, since it's stored in another DB schema and it's main auth identifier
wdyt?

**Comment by rexolion** [comment]
@worm2fed I guess it's ok to move it to security settings, especially if it's easier to implement 👌
