### ISSUE TITLE
Guest wants to sign in to access his account and progress

### ISSUE THREAD

**Issue by worm2fed** [union-platform/union-app#4]
**Scope of action:**  Login Screen
**Precondition:** Guest finished viewing the app information
**Design:** https://www.figma.com/file/2St3zSul4fHnLffqy3WK7P/%5B-union-%5D-mobile?node-id=1160%3A0

## Use cases:

1. The guest enters his email
    (a):
        1. The system informs about an incorrect email, then the script starts from step 1 of the main script
2. The system finds the user in database
    (а):
        1. The system creates a new user in case he doesn't exist
3. The system sends to the guest a one-time password
4. The guest enters the password from the email in the field
    (a):
         1. The system makes the OTP resend button active when the waiting time has expired
         2. The guest clicks on the button to resend an OTP, then the script is repeated from step 2
5. The system checks the entered password
    (a):
        1. The system informs the guest that the OTP is not correct, then the scenario is repeated from step 3
6. The system registers the login information
7. The system redirects the user to the search screen
    (a):
        1. The system redirects the user to the name entry screen if there was no account before

    (b):
        1. The system redirects the user to the profile recovery screen if the account has been deleted and the recovery period has not passed

-----
**Область действия:**  Экран входа
**Предусловие:** Гость завершил просмотр информации о приложении
**Дизайн:** https://www.figma.com/file/2St3zSul4fHnLffqy3WK7P/%5B-union-%5D-mobile?node-id=1160%3A0

## Сценарий:

1. Гость вводит номер телефона
    (а):
        1. Система информирует о некорректном email, далее сценарий проходит с шага 1 основного сценария
2. Система находит в базе пользователя
    (а):
        1. Система создаёт нового пользователя, если его ещё не существует
3. Система высылает пользователю одноразовый пароль
4. Гость вводит пароль из письма в поле
    (а):
        1. Система делает активной кнопку повторной отправки пароля, когда время ожидание истекло
        2. Гость нажимает на кнопку повторной отправки пароля, далее сценарий повторяется с шага 2
5. Система проверяет введённый пароль
    (а):
        1. Система сообщает гостю о том, что пароль не верный, далее сценарий повторяется с шага 3
6. Система регистрирует информацию о входе в систему
7. Система перенаправляет пользователя на экран поиска
    (а):
        1. Система перенаправляет пользователя на экран ввода имени, если учётной записи раньше не было

    (б):
        1. Система перенаправляет пользователя на экран восстановления профиля, если учётная запись была удалена и не прошёл срок для восстановления

**Comment by worm2fed** [comment]
@rexolion be aware that I've edited use case so we use email now; machinery with OTP is still same, for now - no permanent passwords 
pls, make relevant changes in figma

**Comment by rexolion** [comment]
@worm2fed Cool! Do you know how difficult it is to build the **email magic link** functionality as they did in Slack? It will be great to have one.

**Comment by worm2fed** [comment]
@rexolion hm.. I think it's not very hard with my code we can you kinda confirmation code for that but with letters also.

Currently I'm going to send OTP by email (6 digits), but it will be nice to have that link so user do not need to enter OTP manually.

We can allow him either enter digits or click link. It's useful to have both, because sometimes we use mail app in another device.

I like your idea, but I think it's out of scope of this issue. Can you pls create a new one?

**Comment by rexolion** [comment]
@worm2fed Cool created a task https://github.com/union-platform/union-app/issues/134
